In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("nba_games.csv", index_col=0)
df

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,ORtg,DRtg,BPM,home,team,highest_scoring_teammate,opp_team_DRtg,season,date,player
0,D'Angelo Russell,4.0,12.0,0.333,2.0,5.0,0.400,1.0,2.0,0.500,...,91.0,125.0,-6.2,0,LAL,21.0,124.8,2024,2023-10-24,D'Angelo Russell
1,Anthony Davis,6.0,17.0,0.353,1.0,2.0,0.500,4.0,4.0,1.000,...,100.0,122.0,-2.1,0,LAL,21.0,124.8,2024,2023-10-24,Anthony Davis
2,Austin Reaves,4.0,11.0,0.364,1.0,2.0,0.500,5.0,7.0,0.714,...,113.0,121.0,1.5,0,LAL,21.0,124.8,2024,2023-10-24,Austin Reaves
3,Taurean Prince,6.0,8.0,0.750,4.0,6.0,0.667,2.0,2.0,1.000,...,175.0,128.0,11.3,0,LAL,21.0,124.8,2024,2023-10-24,Taurean Prince
4,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,141.0,122.0,11.7,0,LAL,18.0,124.8,2024,2023-10-24,LeBron James
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57834,Kristaps Porziņģis,2.0,4.0,0.500,0.0,2.0,0.000,1.0,2.0,0.500,...,111.0,108.0,-7.9,1,BOS,31.0,122.1,2024,2024-06-17,Kristaps Porziņģis
57835,Luke Kornet,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,231.0,110.0,-1.0,1,BOS,31.0,122.1,2024,2024-06-17,Luke Kornet
57836,Payton Pritchard,1.0,1.0,1.000,1.0,1.0,1.000,0.0,0.0,NaN,...,300.0,110.0,78.6,1,BOS,31.0,122.1,2024,2024-06-17,Payton Pritchard
57837,Oshae Brissett,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,0.0,110.0,-6.0,1,BOS,31.0,122.1,2024,2024-06-17,Oshae Brissett
57838,Svi Mykhailiuk,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,...,0.0,73.0,4.8,1,BOS,31.0,122.1,2024,2024-06-17,Svi Mykhailiuk

In [3]:
def convert_to_seconds(mp):
    try:
        minutes, seconds = map(int, mp.split(':'))
        return minutes * 60 + seconds
    except ValueError:
        return None

In [4]:
df['MP'] = df['MP'].apply(convert_to_seconds)

In [5]:
df['MP']

0        2171.0
1        2049.0
2        1880.0
3        1793.0
4        1740.0
          ...
57834     965.0
57835     122.0
57836      85.0
57837      38.0
57838      38.0
Name: MP, Length: 57839, dtype: float64

In [6]:
df = df.drop("player", axis=1)
df = df.sort_values(by=['Player Name','date'])
df = df.drop_duplicates(subset=['Player Name', 'date'])
df = df.reset_index(drop=True)
df = df.fillna(0)
df

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,USG%,ORtg,DRtg,BPM,home,team,highest_scoring_teammate,opp_team_DRtg,season,date
0,A.J. Green,2.0,2.0,1.000,2.0,2.0,1.000,1.0,1.0,1.000,...,17.7,279.0,127.0,32.2,1,MIL,26.0,106.6,2024,2023-10-29
1,A.J. Green,0.0,4.0,0.000,0.0,3.0,0.000,0.0,0.0,0.000,...,11.0,35.0,121.0,-16.1,1,MIL,33.0,120.2,2024,2023-10-30
2,A.J. Green,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,...,8.3,210.0,137.0,2.8,0,MIL,20.0,136.0,2024,2023-11-01
3,A.J. Green,1.0,3.0,0.333,1.0,3.0,0.333,0.0,0.0,0.000,...,14.2,131.0,118.0,8.2,0,MIL,35.0,115.5,2024,2023-11-11
4,A.J. Green,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,0.000,...,6.2,0.0,130.0,-15.9,0,MIL,37.0,117.5,2024,2023-11-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28936,Zion Williamson,7.0,18.0,0.389,0.0,0.0,0.000,8.0,9.0,0.889,...,31.8,108.0,107.0,-2.1,0,NOP,31.0,106.5,2024,2024-04-09
28937,Zion Williamson,13.0,21.0,0.619,0.0,1.0,0.000,5.0,5.0,1.000,...,39.5,123.0,114.0,6.0,0,NOP,31.0,122.4,2024,2024-04-11
28938,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.500,3.0,6.0,0.500,...,38.3,88.0,99.0,1.2,0,NOP,28.0,110.6,2024,2024-04-12
28939,Zion Williamson,4.0,13.0,0.308,0.0,1.0,0.000,4.0,5.0,0.800,...,24.1,95.0,122.0,-3.3,1,NOP,25.0,108.4,2024,2024-04-14
28940,Zion Williamson,17.0,27.0,0.630,0.0,1.0,0.000,6.0,9.0,0.667,...,40.1,122.0,109.0,0.0,1,NOP,12.0,108.2,2024,2024-04-16

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28941 entries, 0 to 28940
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Player Name               28941 non-null  object
 1   FG                        28941 non-null  float64
 2   FGA                       28941 non-null  float64
 3   FG%                       28941 non-null  float64
 4   3P                        28941 non-null  float64
 5   3PA                       28941 non-null  float64
 6   3P%                       28941 non-null  float64
 7   FT                        28941 non-null  float64
 8   FTA                       28941 non-null  float64
 9   FT%                       28941 non-null  float64
 10  ORB                       28941 non-null  float64
 11  DRB                       28941 non-null  float64
 12  TRB                       28941 non-null  float64
 13  AST                       28941 non-null  float64
 14  STL                       28941 non-null  float64
 15  BLK                       28941 non-null  float64
 16  TOV                       28941 non-null  float64
 17  PF                        28941 non-null  float64
 18  PTS                       28941 non-null  float64
 19  +/-                       28941 non-null  float64
 20  MP                        28941 non-null  float64
 21  TS%                       28941 non-null  float64
 22  eFG%                      28941 non-null  float64
 23  3PAr                      28941 non-null  float64
 24  FTr                       28941 non-null  float64
 25  ORB%                      28941 non-null  float64
 26  DRB%                      28941 non-null  float64
 27  TRB%                      28941 non-null  float64
 28  AST%                      28941 non-null  float64
 29  STL%                      28941 non-null  float64
 30  BLK%                      28941 non-null  float64
 31  TOV%                      28941 non-null  float64
 32  USG%                      28941 non-null  float64
 33  ORtg                      28941 non-null  float64
 34  DRtg                      28941 non-null  float64
 35  BPM                       28941 non-null  float64
 36  home                      28941 non-null  int64
 37  team                      28941 non-null  object
 38  highest_scoring_teammate  28941 non-null  float64
 39  opp_team_DRtg             28941 non-null  float64
 40  season                    28941 non-null  int64
 41  date                      28941 non-null  object
dtypes: float64(37), int64(2), object(3)
memory usage: 9.3+ MB

In [8]:
nulls_df = pd.isnull(df)
nulls_df = nulls_df.sum()
nulls_df[nulls_df > 0]

Series([], dtype: int64)

In [9]:
df['home'].value_counts()

home
1    14492
0    14449
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28941 entries, 0 to 28940
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Player Name               28941 non-null  object
 1   FG                        28941 non-null  float64
 2   FGA                       28941 non-null  float64
 3   FG%                       28941 non-null  float64
 4   3P                        28941 non-null  float64
 5   3PA                       28941 non-null  float64
 6   3P%                       28941 non-null  float64
 7   FT                        28941 non-null  float64
 8   FTA                       28941 non-null  float64
 9   FT%                       28941 non-null  float64
 10  ORB                       28941 non-null  float64
 11  DRB                       28941 non-null  float64
 12  TRB                       28941 non-null  float64
 13  AST                       28941 non-null  float64
 14  STL                       28941 non-null  float64
 15  BLK                       28941 non-null  float64
 16  TOV                       28941 non-null  float64
 17  PF                        28941 non-null  float64
 18  PTS                       28941 non-null  float64
 19  +/-                       28941 non-null  float64
 20  MP                        28941 non-null  float64
 21  TS%                       28941 non-null  float64
 22  eFG%                      28941 non-null  float64
 23  3PAr                      28941 non-null  float64
 24  FTr                       28941 non-null  float64
 25  ORB%                      28941 non-null  float64
 26  DRB%                      28941 non-null  float64
 27  TRB%                      28941 non-null  float64
 28  AST%                      28941 non-null  float64
 29  STL%                      28941 non-null  float64
 30  BLK%                      28941 non-null  float64
 31  TOV%                      28941 non-null  float64
 32  USG%                      28941 non-null  float64
 33  ORtg                      28941 non-null  float64
 34  DRtg                      28941 non-null  float64
 35  BPM                       28941 non-null  float64
 36  home                      28941 non-null  int64
 37  team                      28941 non-null  object
 38  highest_scoring_teammate  28941 non-null  float64
 39  opp_team_DRtg             28941 non-null  float64
 40  season                    28941 non-null  int64
 41  date                      28941 non-null  object
dtypes: float64(37), int64(2), object(3)
memory usage: 9.3+ MB

In [11]:
def add_last_5(player_df, column, n=6):
    for i in range(1, n):
        shifted_values = player_df[column].shift(i)
        shifted_values = shifted_values.fillna(player_df[column])
        player_df[f"{column}_{i}_ago"] = shifted_values
    return player_df

In [12]:
def add_last_5_av(player_df, column, n=7):
    for i in range(3, n):
        sum_list = player_df[[f"{column}_{j}_ago" for j in range(1, i)]].sum(axis=1)
        player_df[f"av_{column}_{i-1}_ago"] = round(sum_list / (i-1))
    return player_df

In [13]:
non_stat_columns = ['date','season','team','Player Name']
stat_columns = df.columns[~df.columns.isin(non_stat_columns)]
stat_columns

Index(['FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-', 'MP',
       'TS%', 'eFG%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%',
       'BLK%', 'TOV%', 'USG%', 'ORtg', 'DRtg', 'BPM', 'home',
       'highest_scoring_teammate', 'opp_team_DRtg'],
      dtype='object')

In [ ]:
for column in stat_columns:
    df = df.groupby("Player Name", group_keys=False).apply(add_last_5,column=column)
    df = df.groupby("Player Name", group_keys=False).apply(add_last_5_av,column=column)

In [ ]:
df = df.copy()

In [ ]:
def add_target(player):
    player["target"] = player["PTS"].shift(-1,fill_value=round(player['PTS'].mean()))
    return player

In [126]:
df = df.groupby("Player Name", group_keys=False).apply(add_target)

In [127]:
df['next_home'] = df['home'].shift(-1,fill_value=2)

In [135]:
nulls_df = pd.isnull(df)
nulls_df = nulls_df.sum()
nulls_df[nulls_df > 0]

Series([], dtype: int64)

In [136]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [137]:
removed_columns = ["season", "date", "target", "team", "team_opp", "Player Name"]

In [138]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28941 entries, 0 to 28940
Columns: 386 entries, Player Name to next_home
dtypes: float64(382), int64(1), object(3)
memory usage: 85.5+ MB

In [139]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [140]:
sfs.fit(df[selected_columns], df["target"])

ValueError:
All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1422, in fit
    X, y, sample_weight, Y = self._prepare_data(X, y, sample_weight, self.solver)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1180, in _prepare_data
    Y = self._label_binarizer.fit_transform(y)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py", line 334, in fit_transform
    return self.fit(y).transform(y)
           ^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py", line 311, in fit
    self.classes_ = unique_labels(y)
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\utils\multiclass.py", line 107, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (array([0.        , 0.02739726, 0.04109589, ..., 0.4109589 , 0.16438356,
       0.21917808]),)

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1422, in fit
    X, y, sample_weight, Y = self._prepare_data(X, y, sample_weight, self.solver)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1180, in _prepare_data
    Y = self._label_binarizer.fit_transform(y)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py", line 334, in fit_transform
    return self.fit(y).transform(y)
           ^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py", line 311, in fit
    self.classes_ = unique_labels(y)
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\utils\multiclass.py", line 107, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (array([0.        , 0.02739726, 0.04109589, ..., 0.12328767, 0.09589041,
       0.04109589]),)

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1422, in fit
    X, y, sample_weight, Y = self._prepare_data(X, y, sample_weight, self.solver)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1180, in _prepare_data
    Y = self._label_binarizer.fit_transform(y)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py", line 334, in fit_transform
    return self.fit(y).transform(y)
           ^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py", line 311, in fit
    self.classes_ = unique_labels(y)
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\blake\anaconda3\Lib\site-packages\sklearn\utils\multiclass.py", line 107, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (array([0.        , 0.02739726, 0.04109589, ..., 0.04109589, 0.16438356,
       0.17808219]),)