In [504]:
import pandas as pd

In [505]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [506]:
df = df.drop("player", axis=1)

In [507]:
df = df.sort_values(by=['Player Name','date'])

In [508]:
df = df.reset_index(drop=True)

In [509]:
df[df["Player Name"] == "LeBron James"].head(10)

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,USG%,ORtg,DRtg,BPM,home,team,highest_scoring_teammate,opp_team_DRtg,season,date
37447,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,24.8,141.0,122.0,11.7,0,LAL,18.0,124.8,2024,2023-10-24
37448,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,24.8,141.0,122.0,11.7,0,LAL,18.0,124.8,2024,2023-10-24
37449,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,24.8,141.0,122.0,11.7,0,LAL,18.0,112.3,2024,2023-10-24
37450,LeBron James,7.0,14.0,0.500,1.0,5.0,0.200,6.0,8.0,0.750,...,27.4,105.0,92.0,10.0,1,LAL,30.0,99.2,2024,2023-10-26
37451,LeBron James,11.0,19.0,0.579,3.0,8.0,0.375,2.0,6.0,0.333,...,32.2,94.0,114.0,0.1,0,LAL,30.0,114.5,2024,2023-10-29
37452,LeBron James,11.0,19.0,0.579,3.0,8.0,0.375,2.0,6.0,0.333,...,32.2,94.0,114.0,0.1,0,LAL,30.0,114.5,2024,2023-10-29
37453,LeBron James,11.0,19.0,0.579,3.0,8.0,0.375,2.0,6.0,0.333,...,32.2,94.0,114.0,0.1,0,LAL,30.0,110.1,2024,2023-10-29
37454,LeBron James,7.0,17.0,0.412,2.0,6.0,0.333,3.0,4.0,0.750,...,33.8,83.0,102.0,-1.9,1,LAL,28.0,107.6,2024,2023-10-30
37455,LeBron James,13.0,19.0,0.684,4.0,8.0,0.500,5.0,10.0,0.500,...,28.5,129.0,111.0,10.5,1,LAL,27.0,118.7,2024,2023-11-01
37456,LeBron James,8.0,15.0,0.533,2.0,5.0,0.400,6.0,7.0,0.857,...,26.1,125.0,111.0,9.9,0,LAL,28.0,121.1,2024,2023-11-04

In [433]:
def add_target(player):
    player["target"] = player["PTS"].shift(-1)
    return player

In [501]:
def add_last_n_games_PTS(player_df, n=5):
    sum_list = []
    for i in range(1,n):
        df[f"PTS_{i}_ago"] = df["PTS"].shift(i)
        if df[f"PTS_{i}_ago"].isna().all():
            print(df["PTS"])
            df[f"PTS_{i}_ago"] = df["PTS"]
        df[f"PTS_{i}_ago"] = df["PTS"].shift(i)
        sum_list.append(df[f"PTS_{i}_ago"])
    sum_list = round(sum(sum_list) / n)
    df["last_5_avg"] = sum_list
    return df

In [ ]:
def add_last_n_games_PTS(player_df, n=5):
    total = list
    for i in range(1,5):
        player_df[f"PTS_{i}_ago"] = df["PTS"].shift(i)

In [ ]:
df = df.groupby("Player Name", group_keys=False).apply(add_target)
df = df.groupby("Player Name", group_keys=False).apply(add_last_n_games_PTS)

In [503]:
df[df["Player Name"] == "LeBron James"].head(10)

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,highest_scoring_teammate,opp_team_DRtg,season,date,target,PTS_1_ago,PTS_2_ago,PTS_3_ago,PTS_4_ago,last_5_avg
37447,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,18.0,124.8,2024,2023-10-24,21.0,NaN,NaN,NaN,NaN,NaN
37448,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,18.0,124.8,2024,2023-10-24,21.0,21.0,NaN,NaN,NaN,NaN
37449,LeBron James,10.0,16.0,0.625,1.0,4.0,0.250,0.0,1.0,0.000,...,18.0,112.3,2024,2023-10-24,21.0,21.0,21.0,NaN,NaN,NaN
37450,LeBron James,7.0,14.0,0.500,1.0,5.0,0.200,6.0,8.0,0.750,...,30.0,99.2,2024,2023-10-26,27.0,21.0,21.0,21.0,NaN,NaN
37451,LeBron James,11.0,19.0,0.579,3.0,8.0,0.375,2.0,6.0,0.333,...,30.0,110.1,2024,2023-10-29,27.0,21.0,21.0,21.0,21.0,17.0
37452,LeBron James,11.0,19.0,0.579,3.0,8.0,0.375,2.0,6.0,0.333,...,30.0,114.5,2024,2023-10-29,27.0,27.0,21.0,21.0,21.0,18.0
37453,LeBron James,11.0,19.0,0.579,3.0,8.0,0.375,2.0,6.0,0.333,...,30.0,114.5,2024,2023-10-29,19.0,27.0,27.0,21.0,21.0,19.0
37454,LeBron James,7.0,17.0,0.412,2.0,6.0,0.333,3.0,4.0,0.750,...,28.0,107.6,2024,2023-10-30,35.0,27.0,27.0,27.0,21.0,20.0
37455,LeBron James,13.0,19.0,0.684,4.0,8.0,0.500,5.0,10.0,0.500,...,27.0,118.7,2024,2023-11-01,24.0,19.0,27.0,27.0,27.0,20.0
37456,LeBron James,8.0,15.0,0.533,2.0,5.0,0.400,6.0,7.0,0.857,...,28.0,121.1,2024,2023-11-04,24.0,35.0,19.0,27.0,27.0,22.0

In [251]:
df = df.copy()

In [252]:
grouped = df.groupby('Player Name')
df['Rolling_Avg'] = round(grouped['PTS'].rolling(window=5, min_periods=1).mean().reset_index(level=0, drop=True))
df['target'] = df['target'].fillna(df['Rolling_Avg'])
df = df.drop(columns=['Rolling_Avg'])

In [253]:
df

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,ORtg,DRtg,BPM,home,team,highest_scoring_teammate,opp_team_DRtg,season,date,target
0,A.J. Green,2.0,2.0,1.000,2.0,2.0,1.0,1.0,1.0,1.000,...,279.0,127.0,32.2,1,MIL,26.0,106.6,2024,2023-10-29,0.0
1,A.J. Green,0.0,4.0,0.000,0.0,3.0,0.0,0.0,0.0,NaN,...,35.0,121.0,-16.1,1,MIL,33.0,120.2,2024,2023-10-30,2.0
2,A.J. Green,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,...,210.0,137.0,2.8,0,MIL,20.0,136.0,2024,2023-11-01,2.0
3,A.J. Green,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,...,210.0,137.0,2.8,0,MIL,20.0,136.0,2024,2023-11-01,2.0
4,A.J. Green,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,...,210.0,137.0,2.8,0,MIL,20.0,116.1,2024,2023-11-01,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57834,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.5,3.0,6.0,0.500,...,88.0,99.0,1.2,0,NOP,28.0,110.6,2024,2024-04-12,26.0
57835,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.5,3.0,6.0,0.500,...,88.0,99.0,1.2,0,NOP,28.0,110.6,2024,2024-04-12,26.0
57836,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.5,3.0,6.0,0.500,...,88.0,99.0,1.2,0,NOP,28.0,115.7,2024,2024-04-12,12.0
57837,Zion Williamson,4.0,13.0,0.308,0.0,1.0,0.0,4.0,5.0,0.800,...,95.0,122.0,-3.3,1,NOP,25.0,108.4,2024,2024-04-14,40.0
57838,Zion Williamson,17.0,27.0,0.630,0.0,1.0,0.0,6.0,9.0,0.667,...,122.0,109.0,NaN,1,NOP,12.0,108.2,2024,2024-04-16,26.0

In [254]:
df["home"].value_counts()

home
0    43347
1    14492
Name: count, dtype: int64

In [255]:
def convert_to_seconds(mp):
    try:
        minutes, seconds = map(int, mp.split(':'))
        return minutes * 60 + seconds
    except ValueError:
        return None

In [256]:
df['MP'] = df['MP'].apply(convert_to_seconds)

In [257]:
nulls = pd.isnull(df)

In [258]:
nulls = nulls.sum()

In [259]:
nulls[nulls > 0]

FG         1432
FGA        1432
FG%        4723
3P         1432
3PA        1432
3P%       14057
FT         1432
FTA        1432
FT%       27583
ORB        1432
DRB        1432
TRB        1432
AST        1432
STL        1432
BLK        1432
TOV        1432
PF         1432
PTS        1432
+/-        1527
MP         1432
TS%        4404
eFG%       4723
3PAr       4723
FTr        4723
ORB%       1457
DRB%       1457
TRB%       1457
AST%       1457
STL%       1457
BLK%       1457
TOV%       3955
USG%       1457
ORtg       1457
DRtg       1457
BPM        1724
target      462
dtype: int64

In [260]:
df = df.fillna(0)

In [261]:
nulls = pd.isnull(df)

In [262]:
nulls = nulls.sum()

In [263]:
nulls

Player Name                 0
FG                          0
FGA                         0
FG%                         0
3P                          0
3PA                         0
3P%                         0
FT                          0
FTA                         0
FT%                         0
ORB                         0
DRB                         0
TRB                         0
AST                         0
STL                         0
BLK                         0
TOV                         0
PF                          0
PTS                         0
+/-                         0
MP                          0
TS%                         0
eFG%                        0
3PAr                        0
FTr                         0
ORB%                        0
DRB%                        0
TRB%                        0
AST%                        0
STL%                        0
BLK%                        0
TOV%                        0
USG%                        0
ORtg                        0
DRtg                        0
BPM                         0
home                        0
team                        0
highest_scoring_teammate    0
opp_team_DRtg               0
season                      0
date                        0
target                      0
dtype: int64

In [264]:
df

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,ORtg,DRtg,BPM,home,team,highest_scoring_teammate,opp_team_DRtg,season,date,target
0,A.J. Green,2.0,2.0,1.000,2.0,2.0,1.0,1.0,1.0,1.000,...,279.0,127.0,32.2,1,MIL,26.0,106.6,2024,2023-10-29,0.0
1,A.J. Green,0.0,4.0,0.000,0.0,3.0,0.0,0.0,0.0,0.000,...,35.0,121.0,-16.1,1,MIL,33.0,120.2,2024,2023-10-30,2.0
2,A.J. Green,1.0,1.0,1.000,0.0,0.0,0.0,0.0,0.0,0.000,...,210.0,137.0,2.8,0,MIL,20.0,136.0,2024,2023-11-01,2.0
3,A.J. Green,1.0,1.0,1.000,0.0,0.0,0.0,0.0,0.0,0.000,...,210.0,137.0,2.8,0,MIL,20.0,136.0,2024,2023-11-01,2.0
4,A.J. Green,1.0,1.0,1.000,0.0,0.0,0.0,0.0,0.0,0.000,...,210.0,137.0,2.8,0,MIL,20.0,116.1,2024,2023-11-01,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57834,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.5,3.0,6.0,0.500,...,88.0,99.0,1.2,0,NOP,28.0,110.6,2024,2024-04-12,26.0
57835,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.5,3.0,6.0,0.500,...,88.0,99.0,1.2,0,NOP,28.0,110.6,2024,2024-04-12,26.0
57836,Zion Williamson,11.0,26.0,0.423,1.0,2.0,0.5,3.0,6.0,0.500,...,88.0,99.0,1.2,0,NOP,28.0,115.7,2024,2024-04-12,12.0
57837,Zion Williamson,4.0,13.0,0.308,0.0,1.0,0.0,4.0,5.0,0.800,...,95.0,122.0,-3.3,1,NOP,25.0,108.4,2024,2024-04-14,40.0
57838,Zion Williamson,17.0,27.0,0.630,0.0,1.0,0.0,6.0,9.0,0.667,...,122.0,109.0,0.0,1,NOP,12.0,108.2,2024,2024-04-16,26.0

In [265]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [266]:
removed_columns = ["season", "date", "target", "team", "team_opp", "Player Name"]

In [267]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [268]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [269]:
df

,Player Name,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,...,ORtg,DRtg,BPM,home,team,highest_scoring_teammate,opp_team_DRtg,season,date,target
0,A.J. Green,0.08,0.042553,1.000,0.166667,0.086957,1.0,0.041667,0.03125,1.000,...,0.930000,0.940625,0.557133,1.0,MIL,0.265625,0.386029,2024,2023-10-29,0.0
1,A.J. Green,0.00,0.085106,0.000,0.000000,0.130435,0.0,0.000000,0.00000,0.000,...,0.116667,0.931250,0.531063,1.0,MIL,0.375000,0.552696,2024,2023-10-30,2.0
2,A.J. Green,0.04,0.021277,1.000,0.000000,0.000000,0.0,0.000000,0.00000,0.000,...,0.700000,0.956250,0.541264,0.0,MIL,0.171875,0.746324,2024,2023-11-01,2.0
3,A.J. Green,0.04,0.021277,1.000,0.000000,0.000000,0.0,0.000000,0.00000,0.000,...,0.700000,0.956250,0.541264,0.0,MIL,0.171875,0.746324,2024,2023-11-01,2.0
4,A.J. Green,0.04,0.021277,1.000,0.000000,0.000000,0.0,0.000000,0.00000,0.000,...,0.700000,0.956250,0.541264,0.0,MIL,0.171875,0.502451,2024,2023-11-01,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57834,Zion Williamson,0.44,0.553191,0.423,0.083333,0.086957,0.5,0.125000,0.18750,0.500,...,0.293333,0.896875,0.540400,0.0,NOP,0.296875,0.435049,2024,2024-04-12,26.0
57835,Zion Williamson,0.44,0.553191,0.423,0.083333,0.086957,0.5,0.125000,0.18750,0.500,...,0.293333,0.896875,0.540400,0.0,NOP,0.296875,0.435049,2024,2024-04-12,26.0
57836,Zion Williamson,0.44,0.553191,0.423,0.083333,0.086957,0.5,0.125000,0.18750,0.500,...,0.293333,0.896875,0.540400,0.0,NOP,0.296875,0.497549,2024,2024-04-12,12.0
57837,Zion Williamson,0.16,0.276596,0.308,0.000000,0.043478,0.0,0.166667,0.15625,0.800,...,0.316667,0.932813,0.537972,1.0,NOP,0.250000,0.408088,2024,2024-04-14,40.0
57838,Zion Williamson,0.68,0.574468,0.630,0.000000,0.043478,0.0,0.250000,0.28125,0.667,...,0.406667,0.912500,0.539753,1.0,NOP,0.046875,0.405637,2024,2024-04-16,26.0

In [270]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [271]:
predictors = list(selected_columns[sfs.get_support()])

In [272]:
predictors

['FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 'FT',
 'ORB',
 'AST',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 '+/-',
 'MP',
 'eFG%',
 '3PAr',
 'ORB%',
 'DRB%',
 'TRB%',
 'AST%',
 'STL%',
 'BLK%',
 'TOV%',
 'ORtg',
 'DRtg',
 'BPM',
 'home',
 'highest_scoring_teammate',
 'opp_team_DRtg']

In [273]:
def backtest(data, model, predictors):
    model.fit(data[predictors], data["target"])
    preds = model.predict(data[predictors])
    preds = pd.Series(preds, index=data.index)
    combined = pd.concat([data["target"], preds], axis=1)
    combined.columns = ["actual", "prediction"]
    return combined

In [274]:
predictions = backtest(df, rr, predictors)

In [275]:
predictions.head(20)

    actual  prediction
0      0.0         3.0
1      2.0         0.0
2      2.0         2.0
3      2.0         2.0
4      3.0         2.0
5      3.0         0.0
6      3.0         0.0
7      0.0         0.0
8      0.0         0.0
9      0.0         0.0
10     6.0         0.0
11     6.0         3.0
12     6.0         3.0
13     8.0         3.0
14     2.0         0.0
15     2.0         0.0
16     2.0         0.0
17     3.0         0.0
18     0.0         0.0
19     0.0         0.0

In [276]:
from sklearn.metrics import accuracy_score
accuracy_score(predictions["actual"], predictions["prediction"])

0.15826691332837706